# TEST_PACKAGE Deployment Script
# Generated by Mock SCCM Server

$credential = Get-Credential
# TODO: Remove hardcoded password
$password = ConvertTo-SecureString 'TempPass123' -AsPlainText -Force
Write-Host 'Installing TEST_PACKAGE...'
# Installation logic here
